# Generated by Django 3.2.9 on 2021-12-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='static/images/cover'),
        ),
    ]
