# Generated by Django 3.2.9 on 2021-12-08 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_file_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adminstrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.administrator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='share.student'),
        ),
    ]
