# Generated by Django 3.2.9 on 2021-12-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_rename_adminstrator_user_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.IntegerField(choices=[(1, 'Activate'), (2, 'Deactivate')], default=1, max_length=5),
        ),
    ]
