# Generated by Django 3.2.9 on 2022-01-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_subject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepermission',
            name='status',
            field=models.IntegerField(choices=[(1, 'Approved'), (2, 'Denied'), (3, 'Pending')], default=3),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.IntegerField(choices=[(1, 'Activate'), (2, 'Deactivate')], default=1),
        ),
    ]
