# Generated by Django 3.2.9 on 2022-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_auto_20220107_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='media/images/cover'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_link',
            field=models.FileField(upload_to='media/documents/'),
        ),
    ]
